	# GNU screen key bindings
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# Improve colors
set -g default-terminal 'screen-256color'

# start window numbers at 1 and make pane numbering consistent with windows
set -g base-index 1

# renumber windows when a window is closed
set -g renumber-windows on

# increase scrollback lines
set -g history-limit 10000
set-option -g default-shell /bin/zsh 
set -g status-bg "colour117"
#set -g status-left '#(tmux-cpu-info)'

# Notifications
#setw -g monitor-activity on
set -g visual-activity on

# invoke reattach-to-user-namespace every time a new window/pane opens
# Need to install this via `brew install reattach-to-user-namespace` 
# set-option -g default-command "reattach-to-user-namespace -l zsh"

# Window && Pane Switching/Resizing Using Mouse
set-option -g mouse on
#set-option -g mouse-select-window on
#set-option -g mouse-select-pane on
#set-option -g mouse-resize-pane on

# Double LMB Select & Copy (Word)
#bind-key -n DoubleClick1Pane \
#    select-pane \; \
#    copy-mode -M \; \
#    send-keys -X select-word \; \
#    run-shell "sleep .5s" \; \
#    send-keys -X copy-pipe-and-cancel "pbcopy"
#bind-key -n DoubleClick1Pane \
#    select-pane \; \
#    copy-mode -M \; \
#    send-keys -X select-word \; \
#    run-shell "sleep .5s" \;
#    send-keys -X copy-pipe-and-cancel "pbcopy"

# Triple LMB Select & Copy (Line)
bind-key -T copy-mode DoubleClick1Pane \
    select-pane \; \
    send-keys -X select-line \; \
    send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -n DoubleClick1Pane \
    select-pane \; \
    copy-mode -M \; \
    send-keys -X select-line \; \
    send-keys -X copy-pipe-and-cancel "pbcopy"
    

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
